# Generated by Django 2.2 on 2018-10-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('tatoeba_id', models.AutoField(primary_key=True,
                                                serialize=False)),
                ('lang', models.CharField(max_length=4)),
                ('content', models.TextField()),
                ('translation', models.ManyToManyField(blank=True,
                                                       to='tatoeba.Sentence')),
            ],
        ),
    ]
